receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4317  # Jaeger's OTLP gRPC endpoint
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: spam_detection
    const_labels:
      service: "spam-detection-service"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
